- type: job
  id: Ataman
  name: Ataman
  description: CARMINETODO
  playTimeTracker: JobAtaman
  weight: 3
  startingGear: AtamanGear
  icon: "JobIconAtaman"
  supervisors: CARMINETODO
  access:
  - Ataman
  - Starshina
  - Consolidat
  requirements:
    - !type:FactionRequirement
      requiredFaction: "IC"
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: Ataman

- type: startingGear
  id: AtamanGear
  equipment:
    shoes: ClothingShoesConsolidatTrench
    jumpsuit: ClothingUniformAtaman
    id: AtamanPDA
    neck: ClothingNeckAtaman
    outerClothing: ClothingFoldsuitAtaman
##  pocket1:
##  pocket2:
    back: ClothingBackpackSatchelLeather
    gloves: ClothingHandsConsolidatFancy
    head: ClothingHeadAtaman
##  mask:
    ears: ClothingHeadsetAtaman
##  belt:
