- type: job
  id: Cepnik
  name: Cepnik
  description: CARMINETODO
  playTimeTracker: JobCepnik
  weight: 1
  startingGear: CepnikGear
  icon: "JobIconCepnik"
  supervisors: CARMINETODO
  access:
  - Consolidat
  requirements:
    - !type:FactionRequirement
      requiredFaction: "IC"
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: Cepnik

- type: startingGear
  id: CepnikGear
  equipment:
    shoes: ClothingShoesConsolidatTrench
    jumpsuit: ClothingUniformHolop
    id: CepnikPDA
    neck: ClothingNeckCepnik
    outerClothing: ClothingFoldsuitCepnik
##  pocket1:
##  pocket2:
    back: ClothingBackpackSatchelLeather
    gloves: ClothingHandsConsolidatTrench
    head: ClothingHeadCepnik
##  mask:
    ears: ClothingHeadsetConsolidat
##  belt:
