- type: job
  id: Dzhigit
  name: Dzhigit
  description: CARMINETODO
  playTimeTracker: JobDzhigit
  weight: 2
  startingGear: DzhigitGear
  icon: "JobIconDzhigit"
  supervisors: CARMINETODO
  access:
  - Consolidat
  - Starshina
  requirements:
    - !type:FactionRequirement
      requiredFaction: "IC"
    - !type:SexRequirement
      requiredSex: "Male"
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: Dzhigit

- type: startingGear
  id: DzhigitGear
  equipment:
    shoes: ClothingShoesConsolidatTrench
    jumpsuit: ClothingUniformStarshina
    id: DzhigitPDA
##  neck:
    outerClothing: ClothingSuitDzhigit
##  pocket1:
##  pocket2:
    back: ClothingBackpackSatchelLeather
    gloves: ClothingHandsConsolidatTrench
    head: ClothingHelmetDzhigit
##  mask:
    ears: ClothingHeadsetConsolidat
##  belt:
