- type: job
  id: Povoznik
  name: Povoznik
  description: CARMINETODO
  playTimeTracker: JobPovoznik
  weight: 1
  startingGear: PovoznikGear
  icon: "JobIconPovoznik"
  supervisors: CARMINETODO
  access:
  - Consolidat
  requirements:
    - !type:FactionRequirement
      requiredFaction: "IC"
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: Povoznik

- type: startingGear
  id: PovoznikGear
  equipment:
    shoes: ClothingShoesConsolidatTrench
    jumpsuit: ClothingUniformHolop
    id: PovoznikPDA
##  neck:
    outerClothing: ClothingFoldsuitPovoznik
##  pocket1:
##  pocket2:
    back: ClothingBackpackSatchelLeather
    gloves: ClothingHandsConsolidatTrench
    head: ClothingHeadPovoznik
##  mask:
    ears: ClothingHeadsetConsolidat
##  belt:
