using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._White.UserInterface.Systems.Movement.Widgets;

[GenerateTypedNameReferences]
public sealed partial class MovementGui : UIWidget
{
    public MovementGui()
    {
        RobustXamlLoader.Load(this);
        var controller = UserInterfaceManager.GetUIController<MovementUIController>();

        MovementButton.OnToggled += _ => controller.ToggleInputMover();
    }

    public void OnInputMoverUpdated(bool sprinting)
    {
        Walking.TextureScale = new (2, 2);
        // CARMINE - .2 NOTE | WD uses a different engine version and some wizardry to fetch "running" as a fucking texture, but we can't or I'm too stupid to figure it out
        //MovementButton.TexturePath = sprinting ? "running" :  "walking";
        Walking.Visible = !sprinting;
        MovementButton.SetClickPressed(sprinting);
    }
}
