# When adding new food also add to random spawner located in Resources\Prototypes\Entities\Markers\Spawners\Random\Food_Drinks\food_produce.yml
# For produce that can't be immediately eaten

- type: entity
  parent: BaseItem
  id: ProduceBase
  abstract: true
  components:
  - type: SolutionContainerManager
  - type: Sprite
    state: produce
  - type: Produce
  - type: PotencyVisuals
  - type: Appearance
  - type: Extractable
    grindableSolutionName: food

- type: entity
  parent: ProduceBase
  id: ProduceBaseRuminant
  abstract: true
  components:
  # let cows eat raw produce like wheat and oats
  - type: Edible
    requiresSpecialDigestion: true
  - type: Tag
    tags:
    - Ruminant

# For produce that can be immediately eaten

- type: entity
  parent: FoodInjectableBase
  id: FoodProduceBase
  abstract: true
  components:
  - type: SolutionContainerManager
  - type: Sprite
    state: produce
  - type: Produce
  - type: PotencyVisuals
  - type: Appearance
  - type: Extractable
    grindableSolutionName: food

# Subclasses

- type: entity
  name: wheat bushel
  description: Sigh... wheat... a-grain?
  id: WheatBushel
  parent: ProduceBaseRuminant
  components:
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/wheat.rsi
  - type: Item
    heldPrefix: produce
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Flour
          Quantity: 10
  - type: Produce
    seedId: wheat
  - type: Tag
    tags:
    - Wheat
    - Ruminant

- type: entity
  name: potato
  parent: FoodProduceBase
  id: FoodPotato
  description: The space Irish starved to death after their potato crops died. Sadly they were unable to fish for space carp due to it being the queen's space. Bringing this up to any space IRA member will drive them insane with anger.
  components:
  - type: FlavorProfile
    flavors:
      - potatoes
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/potato.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: potato
  - type: Tag
    tags:
    - Potato
    - Vegetable
  - type: FoodSequenceElement
    entries:
      Burger: Potato
      Taco: Potato

- type: entity
  name: chanterelle cluster
  parent: FoodProduceBase
  id: FoodMushroom
  description: "Cantharellus Cibarius: These jolly yellow little shrooms sure look tasty!"
  components:
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/chanterelle.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: chanterelle
  - type: Tag
    tags:
    - Vegetable
    - Mushroom

# Slices

- type: entity
  parent: FoodInjectableBase
  id: ProduceSliceBase
  abstract: true
  components:
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 3
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
  - type: Sprite
    state: slice
  - type: Extractable
    grindableSolutionName: food
  - type: Tag
    tags:
    - Slice

- type: entity
  name: rice bushel
  description: Can be ground into rice, perfect for pudding or sake.
  id: RiceBushel
  parent: ProduceBaseRuminant
  components:
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/rice.rsi
  - type: Item
    heldPrefix: produce
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Rice
          Quantity: 10
  - type: Produce
    seedId: rice
