# Overall play time, across all roles.
# This tracker must exist, it is used directly by PlayTimeTrackingManager
- type: playTimeTracker
  id: Overall

# CONSOLIDAT

- type: playTimeTracker
  id: JobHetman

- type: playTimeTracker
  id: JobAtaman

- type: playTimeTracker
  id: JobDzhigit

- type: playTimeTracker
  id: JobNachalnik

- type: playTimeTracker
  id: JobCepnik

- type: playTimeTracker
  id: JobPovoznik

- type: playTimeTracker
  id: JobDoktor
